### ISSUE TITLE
Implement Anchors

### ISSUE THREAD

**Issue by lthibault** [wetware/ww#57]
## Tasks

- [ ] Define Go interface for `Anchor` type
- [ ] Implement `Anchor` fields for `client.Node`
- [ ] Implement `anchor.Host` (cluster host)
- [ ] Implement `anchor.Ref` (memory cells)

## Related Issues

The following issues are related to the task of implementing Anchors.  Some of these may no longer be relevant.

- [ ] #40 
- [ ] #34
